---
abstract: 'Date::Holidays class for GB'
author:
  - 'Michael Jemmeson <mjemmeson@cpan.org>'
build_requires:
  ExtUtils::MakeMaker: 0
  File::Find: 0
  File::Spec::Functions: 0
  File::Temp: 0
  List::Util: 0
  Test::More: 0
  Test::Most: 0
configure_requires:
  ExtUtils::MakeMaker: 6.30
  File::ShareDir::Install: 0.03
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.300034, CPAN::Meta::Converter version 2.120921'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Date-Holidays-GB
no_index:
  directory:
    - t
    - xt
    - examples
    - corpus
  package:
    - DB
provides:
  Date::Holidays::GB:
    file: lib/Date/Holidays/GB.pm
    version: 0.001
requires:
  Date::Holidays::Super: 0
  Exporter: 0
  base: 0
  constant: 0
  perl: 5.008
  strict: 0
  utf8: 0
  warnings: 0
resources:
  bugtracker: https://github.com/mjemmeson/date-holidays-gb/issues
  homepage: https://metacpan.org/release/Date-Holidays-GB
  repository: git://github.com/mjemmeson/date-holidays-gb.git
version: 0.001
